### ISSUE TITLE
Access premium endpoint ?

### ISSUE THREAD

**Issue by jjf21** [nordigen/nordigen-ruby#16]
Hi, I was wondering how to access the premium content. I searched in the lib but didn't find the endpoint for:

`accounts/premium/{id}/transactions/`

[In here](https://github.com/nordigen/nordigen-ruby/blob/master/lib/nordigen_ruby/api/account.rb#L14) shouldn't we add a premium condition in AccountApi:

```ruby
url = if premium
 "#{ENDPOINT}premium/#{@account_id}/"
else 
  "#{ENDPOINT}#{@account_id}/"
end
```

Thanks for your help !

**Comment by victory-sokolov** [comment]
@jjf21 Hey! New version is published.
Please take a look if everything works fine.

Thank you once again for your contribution!

**Comment by jjf21** [comment]
Hey @victory-sokolov , thanks for accepting the PR.
If something break, I'll suggest a correction !
